services:
  php-lint:
    image: php:8.2-cli-alpine
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8080:8080"
    tty: true
    command: php -S 0.0.0.0:8080 -t /workspace
