name: Lint and Deploy

on:
  push:
    branches:
      - feature/gha-test

jobs:
  # 1. 構文チェックジョブ
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Check PHP Syntax Error
        run: |
          if [ -f index.php ]; then
            php -l index.php
          fi

  # 2. デプロイジョブ（構文チェックが成功したら動く）
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          # 指定ファイルのみを明示的にアップロード
          uploads: |
            ./index.html => ~/public_html/proxy/
            ./index.php => ~/public_html/proxy/
            ./style.css => ~/public_html/proxy/
            ./main.js => ~/public_html/proxy/
