name: Lint and Deploy

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # 1. 構文チェックジョブ
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Check PHP Syntax Error
        run: |
          if [ -f index.php ]; then
            php -l index.php
          fi

  # 2. デプロイジョブ
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Inject Cache Busting Version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          sed -i "s/VERSION_PLACEHOLDER/${VERSION}/g" dist/index.html

      - name: FTP Deploy via cURL
        run: |
          SERVER_URL="ftp://${{ secrets.HOST }}/public_html/proxy/"
          USER_PASS="${{ secrets.USER }}:${{ secrets.FTP_PASSWORD }}"

          for file in dist/*; do
            if [ -f "$file" ]; then
              if [[ "$file" == *.json ]]; then
                continue
              fi
              curl -T "$file" "${SERVER_URL}" --user "${USER_PASS}"
            fi
          done
